// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           10
// Async Callback (empty):               1
// Total number of exported functions:  12

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    lottery
    (
        init => init
        startLottery => start_lottery
        buyTicket => buy_ticket
        drawWinner => draw_winner
        resetLottery => reset_lottery
        getStatus => get_status
        getTicketPrice => get_ticket_price
        getPrizePool => get_prize_pool
        getDeadline => get_deadline
        getParticipantCount => get_participant_count
        getWinner => get_winner
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
